# Generated by Django 4.2.6 on 2023-10-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletarget',
            name='users',
            field=models.ManyToManyField(related_name='role_targets', related_query_name='role_target', through='roles.Role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='target',
            field=models.ForeignKey(db_index=False, help_text='The target for this role', on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='roles.roletarget'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, db_index=False, help_text='The user with this role.  If NULL, allows anonymous access to the role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['user', 'type'], name='role_user_type'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('target', 'user', 'type'), name='unique_role_target_user_type'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('target', 'type'), name='unique_role_target_anonymous_type'),
        ),
    ]
