# Generated by Django 4.1.7 on 2023-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['article', 'order'], name='wiki_sectio_article_719adc_idx'),
        ),
    ]
