# Generated by Django 4.2.6 on 2023-10-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Master'), (2, 'Editor'), (3, 'Viewer')], db_index=True, help_text='The role type, like owner, editor, viewer, etc')),
                ('explicit', models.BooleanField(default=True, help_text='Whether this is a manually-applied role.  If this is False, then the role is inherited or implied.')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text="The parent of this RoleTarget, if it's not a root", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='roles.roletarget')),
            ],
        ),
    ]
