# Generated by Django 4.2.6 on 2023-10-28 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Master'), (2, 'Editor'), (3, 'Viewer')], help_text='The role type, like owner, editor, viewer, etc')),
                ('explicit', models.BooleanField(default=True, help_text='Whether this is a manually-applied role.  If this is False, then the role is inherited or implied.')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text="The parent of this RoleTarget, if it's not a root", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='roles.roletarget')),
                ('users', models.ManyToManyField(related_name='role_targets', related_query_name='role_target', through='roles.Role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='target',
            field=models.ForeignKey(help_text='The target for this role', on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='roles.roletarget'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user with this role.  If NULL, allows anonymous access to the role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('target', 'user', 'type'), name='unique_role_target_user_type'),
        ),
    ]
