# Generated by Django 4.2.5 on 2023-10-03 23:40

from importlib.resources import files

from django.db import migrations, models


def uncomment(sql: str) -> str:
    uncommented = [line for line in sql.splitlines() if line.strip() and not line.lstrip().startswith("--")]
    return "\n".join(uncommented)

sql = uncomment((files("worldmaster.roles.migrations") / "0003_create_resolvedrole.sql").read_text("utf-8"))

class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[sql],
            reverse_sql="DROP VIEW roles_resolvedrole",
            state_operations=[
                migrations.CreateModel(
                    name="ResolvedRole",
                    fields=[
                        ("id", models.TextField(primary_key=True, serialize=False)),
                        ("type", models.SlugField(choices=[("master", "Master"), ("editor", "Editor"), ("viewer", "Viewer")], help_text="The role type, like owner, editor, viewer, etc", max_length=16)),
                    ],
                    options={
                        "managed": False,
                    },
                ),
            ],

        ),
    ]
