---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worldmaster-venv
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: worldmaster-dev
spec:
  initContainers:
    - name: init-dev
      image: 'docker.io/worldmasterttrpg/worldmaster:development'
      volumeMounts:
        - mountPath: /opt/worldmaster/work
          name: workdir
        - mountPath: /opt/worldmaster/venv
          name: venv
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: worldmaster.worldmaster.settings.development
        - name: VENV
          value: /opt/worldmaster/venv
      workingDir: /opt/worldmaster/work

      # Disable SELinux security label isolation, otherwise bind mounts don't work.
      securityContext:
        seLinuxOptions:
          type: spc_t
      command:
        - /bin/sh
        - -c
      args:
        - |
          "$VENV/bin/pip" install -e '.[dev]'
  containers:
    - name: dev
      image: 'docker.io/worldmasterttrpg/worldmaster:development'
      volumeMounts:
        - mountPath: /opt/worldmaster/work
          name: workdir
        - mountPath: /opt/worldmaster/venv
          name: venv
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: worldmaster.worldmaster.settings.development
        - name: VENV
          value: /opt/worldmaster/venv
      workingDir: /opt/worldmaster/work

      # Disable SELinux security label isolation, otherwise bind mounts don't work.
      securityContext:
        seLinuxOptions:
          type: spc_t
      command:
        - /bin/sh
        - -c
      args:
        - |
          set -euxf
          # Set up the profile to activate the virtualenv
          for file in profile bash_profile zprofile; do
            echo ". '$VENV/bin/activate'" >> ~/.$file
          done
          while :; do sleep 60; done
  volumes:
    - name: venv
      persistentVolumeClaim:
        claimName: worldmaster-venv
    - name: workdir
      hostPath:
        path: .
