---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worldmaster-venv
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: worldmaster-django
spec:
  initContainers:
    - name: init-postgres
      image: docker.io/postgres:16
      command:
        - sh
        - '-c'
        - |
          set -eux
          i=0

          while [ "$((i += 1))" -le 60 ]; do
            pg_isready -h postgres && exit 0

            sleep 1
          done

          echo "Postgres did not start" >&2
          exit 1

    - name: init-django
      image: 'docker.io/worldmasterttrpg/worldmaster:development'
      volumeMounts:
        - mountPath: /opt/worldmaster/work
          name: workdir
        - mountPath: /opt/worldmaster/venv
          name: venv
        - mountPath: /run/secrets/postgres
          name: postgres
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: worldmaster.worldmaster.settings.development
        - name: VENV
          value: /opt/worldmaster/venv
        - name: DATABASE_PASSWORD_FILE
          value: postgres/password
      workingDir: /opt/worldmaster/work
      securityContext:
        seLinuxOptions:
          type: spc_t
      args:
        - ./containers/django-init.sh
        
  containers:
    - name: django
      image: 'docker.io/worldmasterttrpg/worldmaster:development'
      volumeMounts:
        - mountPath: /opt/worldmaster/work
          name: workdir
        - mountPath: /opt/worldmaster/venv
          name: venv
        - mountPath: /run/secrets/postgres
          name: postgres
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: worldmaster.worldmaster.settings.development
        - name: VENV
          value: /opt/worldmaster/venv
        - name: DATABASE_PASSWORD_FILE
          value: postgres/password
      workingDir: /opt/worldmaster/work
      securityContext:
        seLinuxOptions:
          type: spc_t
      ports:
        - containerPort: 8000
      args:
        - ./containers/runserver.sh
  volumes:
    - name: venv
      persistentVolumeClaim:
        claimName: worldmaster-venv
    - name: postgres
      secret:
        secretName: worldmaster-postgres
    - name: workdir
      hostPath:
        path: .
