---
apiVersion: v1
kind: Secret
metadata:
  name: worldmaster-postgres
data:
  password: KVk/PyQxaF8zPVE7d2R9XDZJWTJwQi1rPytcKnpDYl1qbkdc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worldmaster-postgres
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: worldmaster-postgres
spec:
  containers:
    - name: postgres
      image: 'docker.io/postgis/postgis:16-3.4'
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: worldmaster
        - name: POSTGRES_DB
          value: worldmaster
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: worldmaster-postgres
              key: password
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: worldmaster-postgres
