# Generated by Django 4.2 on 2023-04-06 12:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import worldmaster.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0003_alter_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.article')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wiki.article', models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.article')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wiki.article', models.Model),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.article')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wiki.article', models.Model),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sub_world', serialize=False, to='wiki.article')),
            ],
            options={
                'abstract': False,
            },
            bases=('wiki.article', models.Model),
        ),
        migrations.AddConstraint(
            model_name='world',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_world_slug'),
        ),
        migrations.AddField(
            model_name='plane',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.AddField(
            model_name='event',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.AddField(
            model_name='entity',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.AddConstraint(
            model_name='plane',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_plane_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_event_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_entity_world_slug'),
        ),
    ]
