# Generated by Django 4.2 on 2023-05-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_section_article'),
        ('worlds', '0002_player_world_players_player_unique_player_world_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='event',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='world',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article'),
        ),
    ]
