# Generated by Django 4.2.6 on 2023-10-28 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import worldmaster.worldmaster.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.worldmaster.validators.validate_not_reserved])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article')),
                ('players', models.ManyToManyField(related_name='worlds', related_query_name='world', through='worlds.Player', to=settings.AUTH_USER_MODEL)),
                ('role_target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='roles.roletarget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.worldmaster.validators.validate_not_reserved])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article')),
                ('role_target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='roles.roletarget')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.worldmaster.validators.validate_not_reserved])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article')),
                ('role_target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='roles.roletarget')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.worldmaster.validators.validate_not_reserved])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='wiki.article')),
                ('role_target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='roles.roletarget')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='world',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('world', 'user'), name='unique_player_world_user'),
        ),
        migrations.AddConstraint(
            model_name='plane',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_plane_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_event_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_entity_world_slug'),
        ),
    ]
