# Generated by Django 4.2.6 on 2023-10-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
