# Generated by Django 4.2.6 on 2023-10-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_article_role_target_alter_section_role_target'),
        ('roles', '0002_initial'),
        ('worlds', '0002_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='role_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='roles.roletarget'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='role_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='roles.roletarget'),
        ),
        migrations.AlterField(
            model_name='world',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='world',
            name='role_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='roles.roletarget'),
        ),
    ]
