# Generated by Django 4.1.5 on 2023-01-14 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='world',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
