# Generated by Django 4.1.5 on 2023-02-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='event',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='world',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wiki.article'),
        ),
    ]
