# Generated by Django 4.1.5 on 2023-01-21 04:06

import django.core.validators
from django.db import migrations, models
import worldmaster.validators


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_plane_plane_unique_world_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plane',
            name='unique_world_slug',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='description',
        ),
        migrations.RemoveField(
            model_name='world',
            name='description',
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='plane',
            name='slug',
            field=models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved]),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='world',
            name='slug',
            field=models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved]),
        ),
        migrations.AddConstraint(
            model_name='plane',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_plane_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='world',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_world_slug'),
        ),
    ]
