# Generated by Django 4.1.5 on 2023-01-26 05:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import worldmaster.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('worlds', '0004_remove_plane_unique_world_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='plane',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='world',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.article')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, validators=[django.core.validators.MinLengthValidator(3), worldmaster.validators.validate_not_reserved])),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.article')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_event_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_entity_world_slug'),
        ),
    ]
