# Generated by Django 4.2 on 2023-04-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='target',
            field=models.ForeignKey(help_text='The target for this role', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roles.roletarget'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user with this role.  If NULL, allows anonymous access to the role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roletarget',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text="The parent of this RoleTarget, if it's not a root", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='roles.roletarget'),
        ),
    ]
