# Generated by Django 4.2 on 2023-04-20 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_alter_role_target_alter_role_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletarget',
            name='users',
            field=models.ManyToManyField(related_name='role_targets', related_query_name='role_target', through='roles.Role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('target', 'user', 'type'), name='unique_role_target_user_type'),
        ),
    ]
