# Generated by Django 4.2 on 2023-04-22 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0004_roletarget_users_role_unique_role_target_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='target',
            field=models.ForeignKey(help_text='The target for this role', on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='roles.roletarget'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user with this role.  If NULL, allows anonymous access to the role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
