# Generated by Django 4.2.6 on 2023-11-04 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0003_alter_entity_article_alter_entity_role_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(blank=True, default=None, null=True, verbose_name='The time that this presence appeared')),
                ('end_time', models.FloatField(blank=True, default=None, null=True, verbose_name='The time that this presence disappeared')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(dim=3, srid=4326)),
                ('position', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='The position, or the starting position if end_position is set')),
                ('end_position', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, dim=3, null=True, srid=4326, verbose_name='The end position, if the presence moved')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.entity')),
            ],
        ),
    ]
