# Generated by Django 4.2.7 on 2023-11-06 05:05

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension("postgis"),
    ]
