# Generated by Django 4.2.7 on 2023-11-06 06:08

from django.db import migrations, models
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.CheckConstraint(check=django.db.models.lookups.Exact(lhs=models.Func(models.F('shape'), function='ST_IsClosed'), rhs=True), name='shape_must_be_closed', violation_error_message='If start_time and end_time exist, end_time must be greater than start_time'),
        ),
    ]
