# Generated by Django 4.2.5 on 2023-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.AddField(
            model_name='section',
            name='body',
            field=models.JSONField(default=list, help_text='Article section content'),
        ),
    ]
