# Generated by Django 4.2.6 on 2023-10-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
        ('wiki', '0002_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='role_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='roles.roletarget'),
        ),
        migrations.AlterField(
            model_name='section',
            name='role_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='roles.roletarget'),
        ),
    ]
